name: Java CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update gradle.properties for devMode
        run: |
          sed -i 's/devMode=false/devMode=true/g' gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
